name:                HWord
version:             0.1.0.0
github:              "axect/HWord"
license:             BSD3
author:              "Axect"
maintainer:          "edeftg@gmail.com"
copyright:           "2018 Axect"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Test#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- directory >= 1.3

library:
  source-dirs: src

executables:
  HWord-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HWord

tests:
  HWord-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HWord
